[2024-04-24 10:58:48,414] - 224  werkzeug - INFO- [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-04-24 10:58:48,414] - 224  werkzeug - INFO- [33mPress CTRL+C to quit[0m
[2024-04-24 10:58:57,321] - 109  root - INFO- Dataframe Gathered
[2024-04-24 10:58:57,321] - 110  root - INFO- The cols areIndex(['Category', 'SubCategory', 'days_active', 'R', 'F', 'M', 'Loyalty',
       'Avg Purchase Gap', 'add_to_cart_to_purchase_ratios',
       'add_to_wishlist_to_purchase_ratios',
       'click_wishlist_page_to_purchase_ratios', 'user_path',
       'cart_to_purchase_ratios_category',
       'cart_to_purchase_ratios_subcategory',
       'wishlist_to_purchase_ratios_category',
       'wishlist_to_purchase_ratios_subcategory',
       'click_wishlist_to_purchase_ratios_category',
       'click_wishlist_to_purchase_ratios_subcategory',
       'product_view_to_purchase_ratios_category',
       'product_view_to_purchase_ratios_subcategory'],
      dtype='object')
[2024-04-24 10:58:57,986] - 1744  app - ERROR- Exception on /predict [POST]
Traceback (most recent call last):
  File "D:\Studies\Data Science\ProjectPro Projects\Customer Propensity Model\src\pipeline\prediction_pipeline.py", line 28, in predict
    prediction = model.predict_proba(scaled_features)[:,1]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1372, in predict_proba
    return super()._predict_proba_lr(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 434, in _predict_proba_lr
    prob = self.decision_function(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 921, in check_array
    _assert_all_finite(
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Studies\Data Science\ProjectPro Projects\Customer Propensity Model\app.py", line 56, in predict_datapoint
    pred=predict_pipeline.predict(final_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Studies\Data Science\ProjectPro Projects\Customer Propensity Model\src\pipeline\prediction_pipeline.py", line 34, in predict
    raise CustomException(e,sys)
src.exception.exception.CustomException: Error occured in the python script [ D:\Studies\Data Science\ProjectPro Projects\Customer Propensity Model\src\pipeline\prediction_pipeline.py ] at the line 28 Error message: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
[2024-04-24 10:58:58,002] - 224  werkzeug - INFO- 127.0.0.1 - - [24/Apr/2024 10:58:58] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2024-04-24 10:59:36,728] - 224  werkzeug - INFO- 127.0.0.1 - - [24/Apr/2024 10:59:36] "GET /predict HTTP/1.1" 200 -
[2024-04-24 11:00:10,324] - 109  root - INFO- Dataframe Gathered
[2024-04-24 11:00:10,324] - 110  root - INFO- The cols areIndex(['Category', 'SubCategory', 'days_active', 'R', 'F', 'M', 'Loyalty',
       'Avg Purchase Gap', 'add_to_cart_to_purchase_ratios',
       'add_to_wishlist_to_purchase_ratios',
       'click_wishlist_page_to_purchase_ratios', 'user_path',
       'cart_to_purchase_ratios_category',
       'cart_to_purchase_ratios_subcategory',
       'wishlist_to_purchase_ratios_category',
       'wishlist_to_purchase_ratios_subcategory',
       'click_wishlist_to_purchase_ratios_category',
       'click_wishlist_to_purchase_ratios_subcategory',
       'product_view_to_purchase_ratios_category',
       'product_view_to_purchase_ratios_subcategory'],
      dtype='object')
[2024-04-24 11:00:10,375] - 1744  app - ERROR- Exception on /predict [POST]
Traceback (most recent call last):
  File "D:\Studies\Data Science\ProjectPro Projects\Customer Propensity Model\src\pipeline\prediction_pipeline.py", line 26, in predict
    scaled_features = preprocessor.transform(features)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 658, in transform
    Xt = transform.transform(Xt)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py", line 800, in transform
    Xs = self._fit_transform(
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py", line 658, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\joblib\parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 876, in _transform_one
    res = transformer.transform(X)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\preprocessing\_data.py", line 992, in transform
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\pandas\core\generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'r'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pradyu\anaconda3\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Studies\Data Science\ProjectPro Projects\Customer Propensity Model\app.py", line 56, in predict_datapoint
    pred=predict_pipeline.predict(final_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Studies\Data Science\ProjectPro Projects\Customer Propensity Model\src\pipeline\prediction_pipeline.py", line 34, in predict
    raise CustomException(e,sys)
src.exception.exception.CustomException: Error occured in the python script [ D:\Studies\Data Science\ProjectPro Projects\Customer Propensity Model\src\pipeline\prediction_pipeline.py ] at the line 26 Error message: could not convert string to float: 'r'
[2024-04-24 11:00:10,432] - 224  werkzeug - INFO- 127.0.0.1 - - [24/Apr/2024 11:00:10] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
